apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  allowVolumeExpansion: true
  kind: StorageClass
  metadata:
    name: elastic-storage
    labels:
      8ops.top/study: elastic
  provisioner: kubernetes.io/no-provisioner
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      type: local
      8ops.top/study: elastic
    name: elastic-pv-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: elasticsearch-data-quickstart-es-default-0 # auto generate
      namespace: kube-server
    hostPath:
      path: /data1/pv-10
    persistentVolumeReclaimPolicy: Retain
    storageClassName: elastic-storage
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      type: local
      8ops.top/study: elastic
    name: elastic-pv-1
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: elasticsearch-data-quickstart-es-default-1
      namespace: kube-server
    hostPath:
      path: /data1/pv-11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: elastic-storage
    volumeMode: Filesystem
kind: List
