apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: kube-server
spec:
  version: 7.16.3
  image: "hub.8ops.top/third/kibana:7.16.3"
  count: 1
  elasticsearchRef:
    name: quickstart
