apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-acme.8ops.top 
  namespace: default
spec:
  secretName: tls-acme.8ops.top
  dnsNames:
  - "*.acme.8ops.top"
  issuerRef:
    name: dnspod
    kind: ClusterIssuer
    group: acme.8ops.top
