apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-prometheus
    name: pv-prometheus
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    local:
      path: /opt/data/prometheus
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: prometheus
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-alertmanager
    name: pv-alertmanager
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    local:
      path: /opt/data/alertmanager
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: alertmanager
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-pushgateway
    name: pv-pushgateway
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    local:
      path: /opt/data/pushgateway
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: pushgateway
    volumeMode: Filesystem
kind: List
