apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    labels:
      app.kubernetes.io/instance: prometheus-alert-center
      app.kubernetes.io/name: prometheus-alert-center
    name: prometheus-alert-center
    namespace: kube-server
  subsets:
  - addresses:
    - ip: 10.101.11.236
    ports:
    - name: service
      port: 8090
      protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: prometheus-alert-center
      meta.helm.sh/release-namespace: kube-server
      prometheus.io/scrape: "true"
      prometheus.io/port: "8090"
    labels:
      app.kubernetes.io/instance: prometheus-alert-center
      app.kubernetes.io/name: prometheus-alert-center
    name: prometheus-alert-center
    namespace: kube-server
  spec:
    ports:
    - name: service
      port: 8090
      protocol: TCP
      targetPort: 8090
    type: ClusterIP
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      meta.helm.sh/release-name: prometheus-alert-center
      meta.helm.sh/release-namespace: kube-server
    labels:
      app.kubernetes.io/instance: prometheus-alert-center
      app.kubernetes.io/name: prometheus-alert-center
    name: prometheus-alert-center
    namespace: kube-server
  spec:
    ingressClassName: external
    rules:
    - host: prometheus-alert-center.8ops.top
      http:
        paths:
        - backend:
            service:
              name: prometheus-alert-center
              port:
                number: 8090
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - prometheus-alert-center.8ops.top
      secretName: tls-8ops.top
kind: List
