apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
    app: guestbook
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    name: frontend
