
- hosts: ys
  remote_user: jesse
  tasks:
    - name: test date
      shell: 'date > /tmp/test.txt;date'
      ignore_errors: True
      notify:
        - test cat
    - name: test setenforce
      shell: '/usr/sbin/setenforce 0 || /bin/true'
      become: true
    - name: test copy
      copy: src=/tmp/test.txt dest=/tmp/test.txt
    - name: test copy 2
      copy: 
        src: /tmp/date.txt 
        dest: /tmp/date.txt
  handlers:
    - name: test cat
      shell: 'cat /tmp/test.txt'


