apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: heapster
        #image: lvanneo/heapster-amd64:v1.3.0-beta.1
        image: r.8ops.cc/kubernetes/heapster-amd64:v1.4.1
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
        #- --source=kubernetes:https://kubernetes.default.svc.cluster.local
        #- --sink=influxdb:http://monitoring-influxdb.kube-system.svc.cluster.local:8086
