apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: influxdb
        #image: lvanneo/heapster-influxdb-amd64:v1.1.1
        image: r.8ops.cc/kubernetes/heapster-influxdb-amd64:v1.1.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/
          name: influxdb-config
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: influxdb-config
        configMap:
          name: influxdb-config
