apiVersion: v1
kind: Pod
metadata: 
  name: busybox-namespace-registrykey
  namespace: development
spec: 
  containers: 
  - image: r.8ops.cc/base/busybox
    imagePullPolicy: IfNotPresent
    command: 
      - sleep
      - "3600"
    name: busybox
  imagePullSecrets:
  - name: registrykey
