apiVersion: v1
kind: Pod
metadata:
  name: webapp-hostnetwork
  labels:
    app: webapp
spec:
  hostNetwork: true
  containers:
  - name: webapp
    image: r.8ops.cc/base/tomcat
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: registrykey-tomcat
