apiVersion: v1
kind: Pod
metadata:
  name: webapp-hostport
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: r.8ops.cc/base/tomcat
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      hostPort: 30002
  imagePullSecrets:
  - name: registrykey-tomcat
  dnsPolicy: Default
