image:
  repository: hub.8ops.top/prometheus/blackbox-exporter
  tag: v0.19.0

resources: 
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

service:
  annotations: 
    prometheus.io/scrape: "true"

ingress:
  enabled: true
  className: "external"
  hosts:
    - host: blackbox.8ops.top
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-8ops.top
      hosts:
        - alertmanager.8ops.top


